/**:
  ros__parameters:
    min_longitudinal_offset: 1.93
    max_longitudinal_offset: 2.1
    min_lateral_offset: -0.865
    max_lateral_offset: 1.035
    min_height_offset: 0.934
    max_height_offset: 1.08
